# Install CRAN packages
install.packages("pdftools")
install.packages("tidyverse")
install.packages("tidytext")
install.packages("ggthemes")
install.packages("kableExtra")
install.packages("huxtable")
install.packages("here")
install.packages("gridBase")
install.packages("gridExtra")
install.packages("reshape2")
install.packages("wordcloud")
install.packages("quanteda")
install.packages("Hmisc")
# not available (in required version) for R 3.6.0 > install tag from GitHub
remotes::install_github("tidyverse/googledrive", ref = "v1.0.0", upgrade = "never")
remotes::install_github("tidyverse/googlesheets4", ref = "v0.1.1", upgrade = "never")

# needs development version from a fork, see https://github.com/rstudio/rticles/pull/288
remotes::install_github("nuest/rticles", ref = "LIPIcs")

remotes::install_github("thomasp85/patchwork")
install.packages("ggalluvial")
# https://github.com/clauswilke/colorblindr for checking the figures
remotes::install_github("wilkelab/cowplot")
install.packages("colorspace", repos = "http://R-Forge.R-project.org")
remotes::install_github("clauswilke/colorblindr")

# Install LaTeX packages
tinytex::tlmgr_install("siunitx")
tinytex::tlmgr_install("xcolor")
tinytex::tlmgr_install("colortbl")
tinytex::tlmgr_install("lscape")
tinytex::tlmgr_install("wrapfig")
tinytex::tlmgr_install("float")
tinytex::tlmgr_install("microtype")
tinytex::tlmgr_install("soul")
tinytex::tlmgr_install("multirow")
tinytex::tlmgr_install("babel-english")
tinytex::tlmgr_install("threeparttable")
tinytex::tlmgr_install("lineno")
tinytex::tlmgr_install("lastpage")
tinytex::tlmgr_install("comment")
tinytex::tlmgr_install("xstring")
tinytex::tlmgr_install("thmtools")
tinytex::tlmgr_install("carlisle")
tinytex::tlmgr_install("cleveref")
