# Install CRAN packages
install.packages("pdftools")
install.packages("tidyverse")
install.packages("tidytext")
install.packages("wordcloud")
install.packages("ggthemes")
install.packages("kableExtra")
install.packages("huxtable")
install.packages("here")
install.packages("gridBase")
install.packages("gridExtra")
install.packages("googledrive")
install.packages("googlesheets")

# Install LaTeX packages
tinytex::tlmgr_install("siunitx")
tinytex::tlmgr_install("xcolor")
tinytex::tlmgr_install("colortbl")
tinytex::tlmgr_install("multirow")
tinytex::tlmgr_install("lscape")
tinytex::tlmgr_install("wrapfig")
tinytex::tlmgr_install("float")
