---
title: "Appendix for 'Reproducible Research and GIScience: an evaluation using GIScience conference papers'"
titlerunning: "Reproducible GIScience"
format: "a4paper"
hyphenation: "UKenglish"
authorcolumns: false
numberwithinsect: false # for section-numbered lemmas etc.
cleveref: true # for enabling cleveref support
autoref: true # for enabling autoref support
anonymous: false # for anonymousing the authors (e.g. for double-blind review)
thm-restate: true # for enabling thm-restate support
author:
  # mandatory, please use full name; only 1 author per \author macro; first two parameters are mandatory, other parameters can be empty. Please provide at least the name of the affiliation and the country. The full address is optional
  - name: Frank O. Ostermann
    footnote: Corresponding author
    affiliation: "Faculty of Geo-Information Science and Earth Observation (ITC), University&nbsp;of&nbsp;Twente, Enschede, The Netherlands"
    orcid: "https://orcid.org/0000-0002-9317-8291"
    email: f.o.ostermann@utwente.nl
  - name: Daniel Nüst
    affiliation: "Institute for Geoinformatics, University of Münster, Münster, Germany"
    orcid: "https://orcid.org/0000-0002-0024-5046"
    email: daniel.nuest@uni-muenster.de
    #funding: "Project [_o2r_](https://www.uni-muenster.de/forschungaz/project/12343), German Research Foundation, grant number [PE&nbsp;1632/17-1](https://gepris.dfg.de/gepris/projekt/415851837)."
  - name: Carlos Granell
    affiliation: "Institute of New Imaging Technologies, Universitat Jaume I de Castellón, Castellón, Spain"
    orcid: "https://orcid.org/0000-0003-1004-9695"
    email: carlos.granell@uji.es
    #funding: "Ramón y Cajal Programme of the Spanish government, grant number RYC‐2014‐16913."
  - name: Barbara Hofer
    affiliation: "Christian Doppler Laboratory GEOHUM and Department of Geoinformatics - Z_GIS, University&nbsp;of&nbsp;Salzburg, Salzburg, Austria"
    orcid: "https://orcid.org/0000-0001-7078-3766"
    email: barbara.hofer@sbg.ac.at
  - name: Markus Konkol
    affiliation: "Faculty of Geo-Information Science and Earth Observation (ITC), University&nbsp;of&nbsp;Twente, Enschede, The Netherlands"
    orcid: "https://orcid.org/0000-0001-6651-0976"
    email: m.konkol@utwente.nl
    #funding: "Project [_o2r_](https://www.uni-muenster.de/forschungaz/project/12343), German Research Foundation, grant numbers [KR&nbsp;3930/8-1](https://gepris.dfg.de/gepris/projekt/415851837) and [TR&nbsp;864/12-1]()."
bibliography: bibliography
authorrunning: "F.\\thinspace O. Ostermann, D. Nüst, C. Granell, B. Hofer, M. Konkol" # mandatory. First: Use abbreviated first/middle names. Second (only in severe cases): Use first author plus 'et al.'
ccdesc:
  # Please choose ACM 2012 classifications from https://dl.acm.org/ccs/ccs_flat.cfm
  concept_significance: "500"
  concept_desc: "Information systems~Geographic information systems"
keywords: "reproducible research, open science, reproducibility, GIScience"
# OPTIONAL:
nolinenumbers: true # disable line numbering
hideLIPIcs: true # remove references to LIPIcs series (logo, DOI, ...), e.g. when preparing a pre-final version to be uploaded to arXiv or another public repository
always_allow_html: yes
output:
  bookdown::pdf_book:
    base_format: rticles::lipics_article
    keep_tex: yes
    pandoc_args : ["--verbose"]
header-includes:
  # add packages manually because they are needed for table in the appendix, and that is somehow not picked up
  - \usepackage{longtable}
  - \usepackage{booktabs}
  - \usepackage[table]{xcolor}
  - \interfootnotelinepenalty=10000
abstract: |
  GIScience conference authors and researchers face the same computational reproducibility challenges as authors and researchers from other disciplines who use computers to analyse data.
  Here, to assess the reproducibility of GIScience research, we apply a rubric for assessing the reproducibility of `r count_n`&nbsp;conference papers published at the GIScience conference series in the years 2012-2018.
  Since the rubric and process were previously applied to the publications of the AGILE conference series, this paper itself is an attempt to replicate that analysis, however going beyond the previous work by evaluating and discussing proposed measures to improve reproducibility in the specific context of the GIScience conference series.
  The results of the GIScience paper assessment are in line with previous findings:
  although descriptions of workflows and the inclusion of the data and software suffice to explain the presented work, in most published papers they do not allow a third party to reproduce the results and findings with a reasonable effort.
  We summarise and adapt previous recommendations for improving this situation and propose the GIScience community to start a broad discussion on the reusability, quality, and openness of its research.
  Further, we critically reflect on the process of assessing paper reproducibility, and provide suggestions for improving future assessments.
  The code and data for this article are published at [https://doi.org/10.5281/zenodo.4032875](https://doi.org/10.5281/zenodo.4032875).
---

<!-- DOCUMENT CAN ONLY BE RENDERED AS PORT OF THE MAIN DOCUMENT -->

\newpage

# Appendix
  
```{r corpus-table, echo=FALSE, message=FALSE, warning=FALSE, out.width='100%'}
library("knitr")
library("kableExtra")
library("dplyr")

knitr::kable(paper_evaluation %>%
               select(year, title, `conceptual paper`,
                      `input data`, `preprocessing`, `method/analysis/processing`, `computational environment`, `results`),
      format = "latex",
      longtable = TRUE,
      booktabs = TRUE,
      col.names = c("year", "title", "con-cep-tual",
                    "input data", "pre-proc.", "method/ anal./ proc.", "comp. env.", "results"),
      caption = "Assessment results excerpt; for all fields (including assessors, authors, and assessment comments) see eproducibility package at \\url{https://doi.org/10.5281/zenodo.4032875}.") %>%
  kableExtra::row_spec(0, bold = TRUE) %>%
  kableExtra::column_spec(2, width = "23em") %>%
  kableExtra::column_spec(3, width = "2.8em") %>%
  kableExtra::column_spec(4, width = "2em") %>%
  kableExtra::column_spec(5, width = "2em") %>%
  kableExtra::column_spec(6, width = "2.8em") %>%
  kableExtra::column_spec(7, width = "2em") %>%
  kableExtra::column_spec(8, width = "2.8em") %>%
  kableExtra::kable_styling(latex_options = c("striped", "repeat_header"),
                            font_size = 6)
```


```{r remove_temp_file_appendix}
unlink("temp")
```
